### ISSUE TITLE
Remove the credit card form from Server Side Up

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#163]
### TODO
- [ ] Remove the form
- [ ] Rename the button to "Request Appointment"
- [ ] Remove any order processing things
- [ ] Ensure the process makes sense after removing the payment
- [ ] Make sure the page speed is improved for our book landing page

![Screenshot](https://public-assets.bugflow.io/projects/5/bugs/479/1679008036-screenshot.png)

🌎 URL
-----

https://serversideup.net/get-help/

⚡️ Reported By
--------------

Jay Rogers

🔎 More details
--------------

**Resolution:** 2560x1440

**Viewport Dimensions:** 1280x1302

📎 Attachments
-------------
