### ISSUE TITLE
Add Sevalla as a sponsor ❤️

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#455]
# Background
- [Sevalla](https://sevalla.com/) started sponsoring this project at $750/mo, which is the largest tier on our Sponsorships page

# ToDo
With their Sponsorship, we will complete the following tasks

#### Add logo and link to:
- [x] README
- [x] Docker PHP Homepage
- [x] Docker PHP docs
- [x] Server Side Up blog

I'll need to work with @danpastori to expand some designs and get your logo + link added.

Thanks for your patience @sevalla-hosting. I will be designing this out and we greatly appreciate your Sponsorship 😃👍

**Comment by jaydrogers** [comment]
@danpastori Can we add a sponsors section on the right?

<img width="573" height="696" alt="Image" src="https://github.com/user-attachments/assets/91f2e9d9-0c0a-4e23-9b31-525f14a0a5dc" />

We could also add our sponsor section near the testimonials?

<img width="1075" height="778" alt="Image" src="https://github.com/user-attachments/assets/cf31c7d7-45d1-49c5-b153-9f224f39116b" />

**Comment by jaydrogers** [comment]
I was able to confirm this in the preview here: https://280-create-a-frankenphp-vari.serversideup-php.pages.dev/open-source/docker-php/docs/getting-started

Thanks Dan!

This will be released with v4 🚀
